version: "3"
services:
  auth_service:
    build:
      context: ../../../
      dockerfile: _dockers/prod_single_load_balance/reading_point/app.Dockerfile
    image: reading-point/auth_service:v1.0
    # container_name: reading-point-auth-service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: auth_service
      SERVICE_TAGS: v1
      APP_NAME: auth_service
      APP_ENV: local
      APP_KEY: 28ef3d143ba729acf55d43f3a0f12c65
      APP_DEBUG: 0
      APP_URL: http://localhost
      APP_TIMEZONE: UTC

      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:

      DB_CONNECTION: mysql
      DB_HOST: reading_point_db
      DB_PORT: 3306
      DB_DATABASE: reading_point_auth
      DB_USERNAME: root
      DB_PASSWORD: unpri2022

      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync

    working_dir: /var/www/html

    command: php -S auth_service:8000 -t public
    expose:
      - "8000"
    scale: 3
    networks:
      - reading-point-network
  webserver:
    build:
        context: .
        dockerfile: nginx.Dockerfile
    container_name: reading-point-auth-service-nginx    
    ports:
      - "5100:7100"
    depends_on: 
      - auth_service
    networks:
      - reading-point-network
networks:
  reading-point-network:
    name: reading-point-network
    external: true