version: "3"
services:
  auth_service:
    build:
      context: ../../
      dockerfile: _dockers/prod/Dockerfile
    image: reading-point/auth_service:v1.0
    container_name: reading-point-auth-service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: auth_service
      SERVICE_TAGS: v1
      APP_NAME: auth_service
      APP_ENV: local
      APP_KEY: 28ef3d143ba729acf55d43f3a0f12c65
      APP_DEBUG: 0
      APP_URL: http://localhost
      APP_TIMEZONE: UTC

      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:

      DB_CONNECTION: mysql
      DB_HOST: reading_point_db
      DB_PORT: 3306
      DB_DATABASE: reading_point_auth
      DB_USERNAME: root
      DB_PASSWORD: unpri2022

      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync

    working_dir: /var/www/html

    command: php -S auth_service:8000 -t public
    ports:
      - "8906:8000"
    networks:
      - reading-point-network

  reading_point_db:
    image: mariadb:10.6
    container_name: reading-point-auth-service-db
    volumes:
      - reading-point-auth-service-db:/var/lib/mysql 
    restart: unless-stopped
    tty: true

    environment:
      MYSQL_DATABASE: reading_point_auth
      MYSQL_ROOT_PASSWORD: unpri2022
      SERVICE_TAGS: v1
      SERVICE_NAME: reading_point_db
    networks:
      - reading-point-network
networks:
  reading-point-network:
    driver: bridge
    name: reading-point-auth-network
volumes:
  reading-point-auth-service-db: