version: "3"
services:
  reading_point_db:
    image: mariadb:10.6
    container_name: reading-point-auth-service-db
    volumes:
      - reading-point-auth-service-db:/var/lib/mysql
    restart: unless-stopped
    tty: true

    environment:
      MYSQL_DATABASE: reading_point_auth
      MYSQL_ROOT_PASSWORD: unpri2022
      SERVICE_TAGS: v1
      SERVICE_NAME: reading_point_db
    networks:
      - reading-point-network
networks:
  reading-point-network:
    name: reading-point-network

volumes:
  reading-point-auth-service-db:
    name: reading-point-auth-service-db